-- AVORA beta feedback.
-- Ejecutar una vez en Supabase > SQL Editor para habilitar el formulario de feedback.

create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_email text not null,
  type text not null check (type in ('positive', 'idea', 'bug', 'dislike')),
  message text not null check (char_length(message) between 3 and 2000),
  section text not null default 'Otra',
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  page_path text not null default '',
  user_agent text not null default '',
  app_version text not null default 'beta',
  created_at timestamptz not null default now()
);

alter table public.user_feedback enable row level security;
drop policy if exists owner_access on public.user_feedback;
create policy owner_access on public.user_feedback for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

grant select, insert, update, delete on public.user_feedback to authenticated;
grant usage, select on sequence public.user_feedback_id_seq to authenticated;
