-- AVORA: círculo social (amigos, invitaciones, grupos y objetivos en común).
-- Ejecutar completo una sola vez desde Supabase > SQL Editor, después de schema.sql.
--
-- Idea central: nadie lee los datos crudos de otra persona. Cada cuenta publica
-- una foto mínima de su día en `friend_shares` (Daily Score + racha de uso) y
-- eso es lo único que ven sus amigos. El resto de las tablas siguen cerradas
-- por email como hasta ahora.

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------

-- Amistad como dos filas dirigidas: simplifica las políticas (cada quien ve
-- sólo las suyas) y evita ordenar pares canónicamente en cada consulta.
create table if not exists public.friendships (
  user_email text not null,
  friend_email text not null,
  friend_name text not null default '',
  created_at timestamptz not null default now(),
  primary key (user_email, friend_email)
);

-- Una invitación sirve para los dos caminos: si `to_email` tiene valor es una
-- invitación dirigida que le aparece a esa cuenta dentro de la app; si está
-- vacía es un link para compartir por WhatsApp o mail y lo toma quien lo abra.
create table if not exists public.friend_invites (
  id bigint generated by default as identity primary key,
  code text not null unique,
  from_email text not null,
  from_name text not null default '',
  to_email text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz
);
create index if not exists friend_invites_to_email_idx on public.friend_invites (to_email, status);

-- Lo único que un amigo puede leer de vos: el número del día y la racha.
create table if not exists public.friend_shares (
  user_email text primary key,
  display_name text not null default '',
  share_date text not null default '',
  score integer not null default 0,
  streak integer not null default 0,
  best_streak integer not null default 0,
  headline text not null default '',
  updated_at timestamptz not null default now()
);

-- `groups` es palabra reservada en SQL, así que el nombre lleva prefijo.
create table if not exists public.avora_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  purpose text not null default '',
  accent text not null default 'mint',
  owner_email text not null,
  invite_code text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id bigint not null references public.avora_groups(id) on delete cascade,
  user_email text not null,
  display_name text not null default '',
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  primary key (group_id, user_email)
);
create table if not exists public.group_goals (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.avora_groups(id) on delete cascade,
  title text not null,
  metric text not null default 'count',
  target_value integer not null default 1,
  period text not null default 'weekly',
  due_date text not null default '',
  created_by text not null,
  created_at timestamptz not null default now()
);
-- El aporte de cada integrante a un objetivo del grupo.
create table if not exists public.group_goal_progress (
  goal_id bigint not null references public.group_goals(id) on delete cascade,
  user_email text not null,
  display_name text not null default '',
  value integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (goal_id, user_email)
);

-- ---------------------------------------------------------------------------
-- Ayudantes
-- ---------------------------------------------------------------------------

-- El email de la sesión actual, en un solo lugar.
create or replace function public.avora_email() returns text
  language sql stable set search_path = public as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''))
$$;

-- ¿`other` es amigo mío? `security definer` para que las políticas no dependan
-- de que la sesión pueda leer `friendships` por su cuenta.
create or replace function public.avora_is_friend(other text) returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.friendships f
    where f.user_email = public.avora_email() and f.friend_email = lower(other)
  )
$$;

-- ¿Pertenezco al grupo? Sin `security definer` las políticas de `group_members`
-- se referencian a sí mismas y Postgres corta por recursión infinita.
create or replace function public.avora_in_group(target bigint) returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.group_members m
    where m.group_id = target and m.user_email = public.avora_email()
  )
$$;

create or replace function public.avora_owns_group(target bigint) returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.avora_groups g
    where g.id = target and g.owner_email = public.avora_email()
  )
$$;

create or replace function public.avora_in_goal_group(target bigint) returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from public.group_goals g
    join public.group_members m on m.group_id = g.group_id
    where g.id = target and m.user_email = public.avora_email()
  )
$$;

-- ---------------------------------------------------------------------------
-- Operaciones que no se pueden expresar como una política
-- ---------------------------------------------------------------------------
-- Aceptar una invitación escribe la arista del otro lado, y unirse a un grupo
-- exige leer una fila que todavía no es tuya. Las dos cosas son imposibles bajo
-- RLS desde el cliente, así que viven en funciones `security definer` que
-- validan a mano lo mismo que validaría la política.

-- Las columnas de salida NO pueden llamarse igual que las columnas que toca el
-- cuerpo: `returns table` las declara como variables, y en un `on conflict` no
-- se puede calificar el nombre para desambiguar.
-- `create or replace` no puede cambiar el tipo de retorno de una función que ya
-- existe, así que primero se la borra. El grant se rehace más abajo.
drop function if exists public.avora_accept_friend_invite(text);
create function public.avora_accept_friend_invite(p_code text)
  returns table (accepted_email text, accepted_name text)
  language plpgsql security definer set search_path = public as $$
declare
  me text := public.avora_email();
  my_name text := '';
  invite public.friend_invites%rowtype;
begin
  if me = '' then raise exception 'Necesitás iniciar sesión.'; end if;
  select * into invite from public.friend_invites where code = p_code for update;
  if not found then raise exception 'Esa invitación no existe.'; end if;
  if invite.status <> 'pending' then raise exception 'Esa invitación ya fue usada.'; end if;
  if lower(invite.from_email) = me then raise exception 'No podés aceptar tu propia invitación.'; end if;
  if invite.to_email <> '' and lower(invite.to_email) <> me then
    raise exception 'Esa invitación es para otra cuenta.';
  end if;

  select coalesce(p.display_name, '') into my_name from public.profiles p where lower(p.email) = me;

  insert into public.friendships (user_email, friend_email, friend_name)
    values (me, lower(invite.from_email), invite.from_name)
    on conflict (user_email, friend_email) do update set friend_name = excluded.friend_name;
  insert into public.friendships (user_email, friend_email, friend_name)
    values (lower(invite.from_email), me, coalesce(nullif(my_name, ''), me))
    on conflict (user_email, friend_email) do update set friend_name = excluded.friend_name;

  update public.friend_invites
    set status = 'accepted', responded_at = now(),
        to_email = case when to_email = '' then me else to_email end
    where id = invite.id;

  return query select lower(invite.from_email), invite.from_name;
end $$;

create or replace function public.avora_decline_friend_invite(p_code text)
  returns void language plpgsql security definer set search_path = public as $$
declare
  me text := public.avora_email();
  invite public.friend_invites%rowtype;
begin
  if me = '' then raise exception 'Necesitás iniciar sesión.'; end if;
  select * into invite from public.friend_invites where code = p_code for update;
  if not found then raise exception 'Esa invitación no existe.'; end if;
  if lower(invite.to_email) <> me and lower(invite.from_email) <> me then
    raise exception 'Esa invitación no es tuya.';
  end if;
  update public.friend_invites set status = 'declined', responded_at = now() where id = invite.id;
end $$;

-- Borrar una amistad tiene que borrar las dos aristas; la del otro lado no es
-- visible para esta sesión.
create or replace function public.avora_remove_friend(p_email text)
  returns void language plpgsql security definer set search_path = public as $$
declare me text := public.avora_email(); other text := lower(p_email);
begin
  if me = '' then raise exception 'Necesitás iniciar sesión.'; end if;
  delete from public.friendships where (user_email = me and friend_email = other)
                                    or (user_email = other and friend_email = me);
end $$;

-- Crear un grupo y su primera membresía en una sola transacción: si se hiciera
-- desde el cliente, entre el insert del grupo y el del miembro la fila todavía
-- no pasa su propia política de lectura.
create or replace function public.avora_create_group(p_name text, p_purpose text, p_accent text, p_code text, p_display_name text)
  returns setof public.avora_groups
  language plpgsql security definer set search_path = public as $$
declare me text := public.avora_email(); new_id bigint;
begin
  if me = '' then raise exception 'Necesitás iniciar sesión.'; end if;
  if coalesce(trim(p_name), '') = '' then raise exception 'El grupo necesita un nombre.'; end if;
  insert into public.avora_groups (name, purpose, accent, owner_email, invite_code)
    values (trim(p_name), coalesce(p_purpose, ''), coalesce(nullif(p_accent, ''), 'mint'), me, p_code)
    returning id into new_id;
  insert into public.group_members (group_id, user_email, display_name, role)
    values (new_id, me, coalesce(nullif(p_display_name, ''), me), 'owner');
  return query select * from public.avora_groups where id = new_id;
end $$;

create or replace function public.avora_join_group(p_code text, p_display_name text)
  returns setof public.avora_groups
  language plpgsql security definer set search_path = public as $$
declare me text := public.avora_email(); target public.avora_groups%rowtype;
begin
  if me = '' then raise exception 'Necesitás iniciar sesión.'; end if;
  select * into target from public.avora_groups where invite_code = p_code;
  if not found then raise exception 'Ese grupo no existe o el código venció.'; end if;
  insert into public.group_members (group_id, user_email, display_name, role)
    values (target.id, me, coalesce(nullif(p_display_name, ''), me), 'member')
    on conflict (group_id, user_email) do update set display_name = excluded.display_name;
  return query select * from public.avora_groups where id = target.id;
end $$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.friendships enable row level security;
drop policy if exists friendships_own on public.friendships;
create policy friendships_own on public.friendships for select to authenticated
  using (user_email = public.avora_email());
drop policy if exists friendships_delete on public.friendships;
create policy friendships_delete on public.friendships for delete to authenticated
  using (user_email = public.avora_email());
-- El alta la hace `avora_accept_friend_invite`: no hay política de insert.

alter table public.friend_invites enable row level security;
drop policy if exists friend_invites_visible on public.friend_invites;
create policy friend_invites_visible on public.friend_invites for select to authenticated
  using (lower(from_email) = public.avora_email() or lower(to_email) = public.avora_email());
drop policy if exists friend_invites_send on public.friend_invites;
create policy friend_invites_send on public.friend_invites for insert to authenticated
  with check (lower(from_email) = public.avora_email());
drop policy if exists friend_invites_revoke on public.friend_invites;
create policy friend_invites_revoke on public.friend_invites for update to authenticated
  using (lower(from_email) = public.avora_email())
  with check (lower(from_email) = public.avora_email());
drop policy if exists friend_invites_drop on public.friend_invites;
create policy friend_invites_drop on public.friend_invites for delete to authenticated
  using (lower(from_email) = public.avora_email());

alter table public.friend_shares enable row level security;
drop policy if exists friend_shares_read on public.friend_shares;
create policy friend_shares_read on public.friend_shares for select to authenticated
  using (user_email = public.avora_email() or public.avora_is_friend(user_email));
drop policy if exists friend_shares_write on public.friend_shares;
create policy friend_shares_write on public.friend_shares for insert to authenticated
  with check (user_email = public.avora_email());
drop policy if exists friend_shares_update on public.friend_shares;
create policy friend_shares_update on public.friend_shares for update to authenticated
  using (user_email = public.avora_email()) with check (user_email = public.avora_email());

alter table public.avora_groups enable row level security;
drop policy if exists groups_member_read on public.avora_groups;
create policy groups_member_read on public.avora_groups for select to authenticated
  using (public.avora_in_group(id));
drop policy if exists groups_owner_write on public.avora_groups;
create policy groups_owner_write on public.avora_groups for update to authenticated
  using (owner_email = public.avora_email()) with check (owner_email = public.avora_email());
drop policy if exists groups_owner_delete on public.avora_groups;
create policy groups_owner_delete on public.avora_groups for delete to authenticated
  using (owner_email = public.avora_email());
-- El alta la hace `avora_create_group`.

alter table public.group_members enable row level security;
drop policy if exists group_members_read on public.group_members;
create policy group_members_read on public.group_members for select to authenticated
  using (public.avora_in_group(group_id));
-- Sumás gente al grupo sólo si ya sos parte y esa persona ya es amiga tuya.
drop policy if exists group_members_add on public.group_members;
create policy group_members_add on public.group_members for insert to authenticated
  with check (public.avora_in_group(group_id) and public.avora_is_friend(user_email));
drop policy if exists group_members_leave on public.group_members;
create policy group_members_leave on public.group_members for delete to authenticated
  using (user_email = public.avora_email() or public.avora_owns_group(group_id));

alter table public.group_goals enable row level security;
drop policy if exists group_goals_read on public.group_goals;
create policy group_goals_read on public.group_goals for select to authenticated
  using (public.avora_in_group(group_id));
drop policy if exists group_goals_add on public.group_goals;
create policy group_goals_add on public.group_goals for insert to authenticated
  with check (public.avora_in_group(group_id) and lower(created_by) = public.avora_email());
drop policy if exists group_goals_edit on public.group_goals;
create policy group_goals_edit on public.group_goals for update to authenticated
  using (public.avora_in_group(group_id)) with check (public.avora_in_group(group_id));
drop policy if exists group_goals_drop on public.group_goals;
create policy group_goals_drop on public.group_goals for delete to authenticated
  using (lower(created_by) = public.avora_email() or public.avora_owns_group(group_id));

alter table public.group_goal_progress enable row level security;
drop policy if exists goal_progress_read on public.group_goal_progress;
create policy goal_progress_read on public.group_goal_progress for select to authenticated
  using (public.avora_in_goal_group(goal_id));
drop policy if exists goal_progress_write on public.group_goal_progress;
create policy goal_progress_write on public.group_goal_progress for insert to authenticated
  with check (user_email = public.avora_email() and public.avora_in_goal_group(goal_id));
drop policy if exists goal_progress_update on public.group_goal_progress;
create policy goal_progress_update on public.group_goal_progress for update to authenticated
  using (user_email = public.avora_email()) with check (user_email = public.avora_email());
drop policy if exists goal_progress_drop on public.group_goal_progress;
create policy goal_progress_drop on public.group_goal_progress for delete to authenticated
  using (user_email = public.avora_email());

-- ---------------------------------------------------------------------------
-- Permisos
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on
  public.friendships, public.friend_invites, public.friend_shares,
  public.avora_groups, public.group_members, public.group_goals, public.group_goal_progress
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.avora_email() to authenticated;
grant execute on function public.avora_is_friend(text) to authenticated;
grant execute on function public.avora_in_group(bigint) to authenticated;
grant execute on function public.avora_owns_group(bigint) to authenticated;
grant execute on function public.avora_in_goal_group(bigint) to authenticated;
grant execute on function public.avora_accept_friend_invite(text) to authenticated;
grant execute on function public.avora_decline_friend_invite(text) to authenticated;
grant execute on function public.avora_remove_friend(text) to authenticated;
grant execute on function public.avora_create_group(text, text, text, text, text) to authenticated;
grant execute on function public.avora_join_group(text, text) to authenticated;
