-- AVORA: preferencias y dispositivos para notificaciones push.
-- Ejecutar una vez en Supabase > SQL Editor.

create table if not exists public.notification_preferences (
  user_email text primary key references public.profiles(email) on delete cascade,
  push_enabled boolean not null default false,
  calendar_enabled boolean not null default true,
  daily_balance_enabled boolean not null default true,
  weekly_summary_enabled boolean not null default true,
  monthly_summary_enabled boolean not null default true,
  annual_summary_enabled boolean not null default true,
  calendar_reminder_time text not null default '18:00',
  daily_balance_time text not null default '21:00',
  weekly_summary_time text not null default '20:00',
  monthly_summary_time text not null default '20:00',
  annual_summary_time text not null default '20:00',
  timezone text not null default 'America/Argentina/Buenos_Aires',
  updated_at timestamptz not null default now(),
  constraint notification_preferences_calendar_time check (calendar_reminder_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  constraint notification_preferences_daily_time check (daily_balance_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  constraint notification_preferences_weekly_time check (weekly_summary_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  constraint notification_preferences_monthly_time check (monthly_summary_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  constraint notification_preferences_annual_time check (annual_summary_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_email text not null references public.profiles(email) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_email, endpoint)
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_email text not null references public.profiles(email) on delete cascade,
  kind text not null,
  reference_key text not null,
  sent_at timestamptz not null default now(),
  unique(user_email, kind, reference_key)
);

alter table public.notification_preferences enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists owner_access on public.notification_preferences;
create policy owner_access on public.notification_preferences for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

drop policy if exists owner_access on public.push_subscriptions;
create policy owner_access on public.push_subscriptions for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

drop policy if exists owner_access on public.notification_deliveries;
create policy owner_access on public.notification_deliveries for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

grant select, insert, update, delete on public.notification_preferences to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant select, insert, update, delete on public.notification_deliveries to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;
grant usage, select on sequence public.notification_deliveries_id_seq to authenticated;
