-- AVORA: esquema inicial para Supabase/Postgres.
-- Ejecutar completo una sola vez desde Supabase > SQL Editor.

create table if not exists public.profiles (
  email text primary key,
  display_name text not null,
  onboarding_completed boolean not null default false,
  main_goals_json text not null default '[]',
  usage_preferences_json text not null default '[]',
  pro_since text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.gym_attendance (
  id bigint generated by default as identity primary key, user_email text not null, attended_date text not null,
  created_at timestamptz not null default now(), unique(user_email, attended_date)
);
create table if not exists public.meals (
  id bigint generated by default as identity primary key, user_email text not null, meal_date text not null,
  name text not null, detail text not null default '', calories integer not null default 0,
  protein integer not null default 0, carbs integer not null default 0, fat integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.diet_plans (
  id bigint generated by default as identity primary key, user_email text not null unique, age integer not null,
  sex text not null default 'unspecified', height_cm integer not null, current_weight_deci_kg integer not null,
  target_weight_deci_kg integer not null, activity_level text not null default 'light', goal_pace text not null default 'gentle',
  preferences text not null default '', details text not null default '', target_calories integer not null, plan_json text not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.books (
  id bigint generated by default as identity primary key, user_email text not null, title text not null,
  author text not null default '', status text not null default 'reading', total_pages integer not null default 0,
  current_page integer not null default 0, cover_url text not null default '', external_key text not null default '',
  created_at timestamptz not null default now()
);
create table if not exists public.reading_logs (
  id bigint generated by default as identity primary key, user_email text not null,
  book_id bigint not null references public.books(id) on delete cascade, log_date text not null,
  pages integer not null default 0, minutes integer not null default 0, updated_at timestamptz not null default now(),
  unique(user_email, book_id, log_date)
);
create table if not exists public.book_notes (
  id bigint generated by default as identity primary key, user_email text not null,
  book_id bigint not null references public.books(id) on delete cascade, content text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.monthly_priorities (
  id bigint generated by default as identity primary key, user_email text not null, month_key text not null,
  gym_weight integer not null default 2, nutrition_weight integer not null default 2, reading_weight integer not null default 2,
  sleep_weight integer not null default 2, focus_weight integer not null default 2, goals_weight integer not null default 2,
  updated_at timestamptz not null default now(), unique(user_email, month_key)
);
create table if not exists public.goals (
  id bigint generated by default as identity primary key, user_email text not null, title text not null,
  period text not null, category text not null default 'general', target_date text not null,
  completed_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.daily_checkins (
  id bigint generated by default as identity primary key, user_email text not null, entry_date text not null,
  habits_json text not null default '[]', workout_detail text not null default '', study_minutes integer not null default 0,
  study_detail text not null default '', sleep_minutes integer not null default 0, bedtime text not null default '',
  wake_time text not null default '', water_ml integer not null default 0, journal text not null default '',
  transcript text not null default '', voice_summary text not null default '', updated_at timestamptz not null default now(),
  unique(user_email, entry_date)
);
create table if not exists public.training_disciplines (
  id bigint generated by default as identity primary key, user_email text not null, name text not null,
  kind text not null default 'other', created_at timestamptz not null default now(), unique(user_email, name)
);
create table if not exists public.training_logs (
  id bigint generated by default as identity primary key, user_email text not null,
  discipline_id bigint not null references public.training_disciplines(id) on delete cascade, training_date text not null,
  duration_minutes integer not null default 0, distance_meters integer not null default 0, notes text not null default '',
  created_at timestamptz not null default now(), unique(user_email, discipline_id, training_date)
);
create table if not exists public.exercise_logs (
  id bigint generated by default as identity primary key, user_email text not null,
  training_log_id bigint not null references public.training_logs(id) on delete cascade, exercise text not null,
  weight_deci_kg integer not null default 0, sets integer not null default 0, reps integer not null default 0,
  is_record boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.focus_projects (
  id bigint generated by default as identity primary key, user_email text not null, name text not null,
  kind text not null default 'study', created_at timestamptz not null default now(), unique(user_email, name)
);
create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key, user_email text not null,
  project_id bigint not null references public.focus_projects(id) on delete cascade, session_date text not null,
  minutes integer not null default 0, note text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.tasks (
  id bigint generated by default as identity primary key, user_email text not null,
  project_id bigint references public.focus_projects(id) on delete set null, title text not null, due_date text,
  start_time text not null default '', duration_minutes integer not null default 0, completed_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key, user_email text not null, title text not null,
  event_date text not null, event_time text not null default '', duration_minutes integer not null default 60,
  category text not null default 'personal', notes text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_email text not null,
  type text not null check (type in ('positive', 'idea', 'bug', 'dislike')),
  message text not null check (char_length(message) between 3 and 2000),
  section text not null default 'Otra',
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  page_path text not null default '',
  user_agent text not null default '',
  app_version text not null default 'beta',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
drop policy if exists profiles_owner on public.profiles;
create policy profiles_owner on public.profiles for all to authenticated
  using (email = (select auth.jwt() ->> 'email'))
  with check (email = (select auth.jwt() ->> 'email'));

do $policies$
declare table_name text;
begin
  foreach table_name in array array[
    'gym_attendance','meals','diet_plans','books','reading_logs','book_notes','monthly_priorities','goals',
    'daily_checkins','training_disciplines','training_logs','exercise_logs','focus_projects','focus_sessions','tasks','calendar_events','user_feedback'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists owner_access on public.%I', table_name);
    execute format(
      'create policy owner_access on public.%I for all to authenticated using (user_email = (select auth.jwt() ->> ''email'')) with check (user_email = (select auth.jwt() ->> ''email''))',
      table_name
    );
  end loop;
end
$policies$;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
