-- Estudio: artículos, podcasts y videos guardados, cada uno con sus notas.
-- Ejecutar una vez en Supabase > SQL Editor. Mientras no exista, la app sigue
-- funcionando y simplemente muestra la lista vacía.
create table if not exists public.study_resources (
  id bigint generated by default as identity primary key,
  user_email text not null,
  kind text not null default 'article' check (kind in ('article', 'podcast', 'video')),
  title text not null check (char_length(title) between 1 and 200),
  author text not null default '',
  url text not null default '',
  status text not null default 'pending' check (status in ('pending', 'done')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists study_resources_user_email_idx on public.study_resources (user_email);

create table if not exists public.resource_notes (
  id bigint generated by default as identity primary key,
  user_email text not null,
  resource_id bigint not null references public.study_resources(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);
create index if not exists resource_notes_user_email_idx on public.resource_notes (user_email);

do $policies$
declare table_name text;
begin
  foreach table_name in array array['study_resources', 'resource_notes'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists owner_access on public.%I', table_name);
    execute format(
      'create policy owner_access on public.%I for all to authenticated using (user_email = (select auth.jwt() ->> ''email'')) with check (user_email = (select auth.jwt() ->> ''email''))',
      table_name
    );
  end loop;
end
$policies$;

grant select, insert, update, delete on public.study_resources, public.resource_notes to authenticated;
grant usage, select on sequence public.study_resources_id_seq, public.resource_notes_id_seq to authenticated;
