-- Revisión semanal con IA, disponible sólo para cuentas Pro.
-- Ejecutar una sola vez desde Supabase > SQL Editor. Es aditivo.

create table if not exists public.weekly_ai_reviews (
  id bigint generated by default as identity primary key,
  user_email text not null,
  week_start date not null,
  week_end date not null,
  status text not null default 'pending'
    check (status in ('pending', 'ready', 'failed')),
  result_json jsonb not null default '{}'::jsonb,
  metrics_json jsonb not null default '{}'::jsonb,
  context_used boolean not null default false,
  model text not null default '',
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_email, week_start)
);

alter table public.weekly_ai_reviews
  add column if not exists context_used boolean not null default false;

create index if not exists weekly_ai_reviews_user_week_idx
  on public.weekly_ai_reviews (user_email, week_start desc);

alter table public.weekly_ai_reviews enable row level security;
drop policy if exists owner_access on public.weekly_ai_reviews;
create policy owner_access on public.weekly_ai_reviews for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

create table if not exists public.weekly_ai_memory (
  id bigint generated by default as identity primary key,
  user_email text not null,
  memory_key text not null,
  category text not null
    check (category in ('preference', 'priority', 'availability', 'temporary_constraint')),
  content text not null,
  valid_until date,
  source_week_start date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_email, memory_key)
);

create index if not exists weekly_ai_memory_user_expiry_idx
  on public.weekly_ai_memory (user_email, valid_until);

alter table public.weekly_ai_memory enable row level security;
drop policy if exists owner_access on public.weekly_ai_memory;
create policy owner_access on public.weekly_ai_memory for all to authenticated
  using (user_email = (select auth.jwt() ->> 'email'))
  with check (user_email = (select auth.jwt() ->> 'email'));

grant select, insert, update, delete on public.weekly_ai_reviews, public.weekly_ai_memory to authenticated;
grant usage, select on sequence public.weekly_ai_reviews_id_seq, public.weekly_ai_memory_id_seq to authenticated;
