import { ok, fail, patched } from "@/server/http";
import { deleteRows, insertRows } from "@/server/db/postgrest";
import { owned, upsert } from "@/server/db/rows";
import type { ProgressRow } from "@/server/db/rows";
import { DATE } from "@/domain/validation";
import type { ActionMap } from "@/server/progress/types";

export const nutritionActions: ActionMap = {
  add_meal: async ({ p, email }) => { const date = String(p.date ?? ""), name = String(p.name ?? "").trim(); if (!DATE.test(date) || !name) return fail("Completá el nombre y la fecha."); const rows = await insertRows<ProgressRow>("meals", { userEmail: email, mealDate: date, name, detail: String(p.detail ?? "").trim(), calories: Math.max(0, Math.min(10000, Number(p.calories) || 0)), protein: Math.max(0, Math.min(1000, Number(p.protein) || 0)), carbs: Math.max(0, Math.min(2000, Number(p.carbs) || 0)), fat: Math.max(0, Math.min(1000, Number(p.fat) || 0)) }, { returnRows: true }); return patched({ upsert: { mealHistory: rows } }); },
  delete_meal: async ({ p, email }) => { const id = Number(p.id); await deleteRows("meals", { id, userEmail: email }); return patched({ remove: { mealHistory: [id] } }); },
  save_diet_plan: async ({ p, email }) => { const age = Math.round(Number(p.age) || 0), heightCm = Math.round(Number(p.heightCm) || 0), currentWeightDeciKg = Math.round((Number(p.currentWeightKg) || 0) * 10), targetWeightDeciKg = Math.round((Number(p.targetWeightKg) || 0) * 10), targetCalories = Math.round(Number(p.targetCalories) || 0); if (age < 18 || age > 100 || heightCm < 120 || heightCm > 230 || currentWeightDeciKg < 350 || targetWeightDeciKg < 350 || !p.plan || targetCalories < 1000 || targetCalories > 6000) return fail("Revisá los datos del plan."); await upsert("diet_plans", { userEmail: email, age, sex: String(p.sex ?? "unspecified"), heightCm, currentWeightDeciKg, targetWeightDeciKg, activityLevel: String(p.activityLevel ?? "light"), goalPace: String(p.goalPace ?? "gentle"), preferences: String(p.preferences ?? "").slice(0, 500), details: String(p.details ?? "").slice(0, 2000), targetCalories, planJson: JSON.stringify(p.plan).slice(0, 30000) }, ["userEmail"]); return ok(); },
  // Calculadora rápida sin IA: solo fija las calorías objetivo (y el snapshot biométrico que las produjo). Nunca toca planJson/preferences/details de un plan con IA ya guardado.
  set_diet_target: async ({ p, email }) => { const age = Math.round(Number(p.age) || 0), heightCm = Math.round(Number(p.heightCm) || 0), currentWeightDeciKg = Math.round((Number(p.currentWeightKg) || 0) * 10), targetWeightDeciKg = Math.round((Number(p.targetWeightKg) || 0) * 10), targetCalories = Math.round(Number(p.targetCalories) || 0); if (age < 18 || age > 100 || heightCm < 120 || heightCm > 230 || currentWeightDeciKg < 350 || targetWeightDeciKg < 350 || targetCalories < 1000 || targetCalories > 6000) return fail("Revisá los datos."); const existing = (await owned("diet_plans", email))[0]; await upsert("diet_plans", { userEmail: email, age, sex: String(p.sex ?? "unspecified"), heightCm, currentWeightDeciKg, targetWeightDeciKg, activityLevel: String(p.activityLevel ?? "light"), goalPace: String(p.goalPace ?? "gentle"), preferences: String(existing?.preferences ?? ""), details: String(existing?.details ?? ""), targetCalories, planJson: String(existing?.planJson ?? "") }, ["userEmail"]); return ok(); },
};
