import type { FoodServing } from "@/features/nutrition/logic/nutrition-tracker";

export const FOOD_CATEGORIES = [
  "Frutas",
  "Verduras y acompañamientos",
  "Proteínas",
  "Cereales y panificados",
  "Lácteos",
  "Comidas argentinas",
  "Extras",
] as const;

export const FOOD_LIBRARY: FoodServing[] = [
  { id: "banana", name: "Banana", category: "Frutas", portion: "1 unidad mediana (90 g)", calories: 80, protein: 1, carbs: 20, fat: 0.2, keywords: ["platano"] },
  { id: "manzana", name: "Manzana", category: "Frutas", portion: "1 unidad (150 g)", calories: 78, protein: 0.4, carbs: 21, fat: 0.3 },
  { id: "naranja", name: "Naranja", category: "Frutas", portion: "1 unidad (130 g)", calories: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { id: "pera", name: "Pera", category: "Frutas", portion: "1 unidad (150 g)", calories: 86, protein: 0.6, carbs: 23, fat: 0.2 },
  { id: "palta", name: "Palta", category: "Frutas", portion: "1/2 unidad (70 g)", calories: 112, protein: 1.4, carbs: 6, fat: 10, keywords: ["aguacate"] },
  { id: "tomate", name: "Tomate", category: "Verduras y acompañamientos", portion: "1 unidad (120 g)", calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },
  { id: "ensalada", name: "Ensalada mixta", category: "Verduras y acompañamientos", portion: "1 plato chico (150 g)", calories: 55, protein: 2, carbs: 11, fat: 0.5 },
  { id: "brocoli", name: "Brócoli", category: "Verduras y acompañamientos", portion: "1 taza (150 g)", calories: 52, protein: 3.6, carbs: 10.8, fat: 0.6 },
  { id: "papa", name: "Papa hervida", category: "Verduras y acompañamientos", portion: "1 unidad chica (150 g)", calories: 130, protein: 2.8, carbs: 30, fat: 0.2 },
  { id: "batata", name: "Batata al horno", category: "Verduras y acompañamientos", portion: "1 unidad chica (150 g)", calories: 135, protein: 2.5, carbs: 31, fat: 0.2 },
  { id: "pollo", name: "Pollo sin piel", category: "Proteínas", portion: "1 porción (120 g)", calories: 198, protein: 37, carbs: 0, fat: 4.3 },
  { id: "huevo", name: "Huevo", category: "Proteínas", portion: "1 unidad", calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8 },
  { id: "carne", name: "Carne vacuna magra", category: "Proteínas", portion: "1 porción (120 g)", calories: 255, protein: 31, carbs: 0, fat: 14 },
  { id: "atun", name: "Atún al natural", category: "Proteínas", portion: "1/2 lata escurrida (80 g)", calories: 93, protein: 20, carbs: 0, fat: 1 },
  { id: "salmon", name: "Salmón", category: "Proteínas", portion: "1 porción (120 g)", calories: 250, protein: 25, carbs: 0, fat: 15 },
  { id: "lentejas", name: "Lentejas cocidas", category: "Proteínas", portion: "3/4 taza (150 g)", calories: 174, protein: 13.5, carbs: 30, fat: 0.6 },
  { id: "arroz", name: "Arroz cocido", category: "Cereales y panificados", portion: "3/4 taza (150 g)", calories: 195, protein: 4, carbs: 42, fat: 0.4 },
  { id: "fideos", name: "Fideos cocidos", category: "Cereales y panificados", portion: "1 plato (180 g)", calories: 280, protein: 10, carbs: 55, fat: 1.5 },
  { id: "avena", name: "Avena", category: "Cereales y panificados", portion: "1/2 taza (40 g)", calories: 156, protein: 6.8, carbs: 26.5, fat: 2.8 },
  { id: "pan", name: "Pan", category: "Cereales y panificados", portion: "1 rodaja (35 g)", calories: 92, protein: 3, carbs: 17, fat: 1.2 },
  { id: "tortilla", name: "Tortilla de trigo", category: "Cereales y panificados", portion: "1 unidad (60 g)", calories: 190, protein: 5, carbs: 31, fat: 5 },
  { id: "leche", name: "Leche", category: "Lácteos", portion: "1 vaso (200 ml)", calories: 100, protein: 6.6, carbs: 9.6, fat: 3.4 },
  { id: "yogur", name: "Yogur natural", category: "Lácteos", portion: "1 pote (170 g)", calories: 105, protein: 6, carbs: 12, fat: 3 },
  { id: "yogur-griego", name: "Yogur griego", category: "Lácteos", portion: "1 pote (170 g)", calories: 140, protein: 16, carbs: 9, fat: 4 },
  { id: "queso", name: "Queso semiduro", category: "Lácteos", portion: "1 feta gruesa (30 g)", calories: 110, protein: 7, carbs: 1, fat: 9 },
  { id: "ricota", name: "Ricota", category: "Lácteos", portion: "1/4 taza (60 g)", calories: 104, protein: 7, carbs: 3, fat: 7 },
  { id: "empanada-carne", name: "Empanada de carne", category: "Comidas argentinas", portion: "1 unidad al horno", calories: 220, protein: 11, carbs: 22, fat: 10 },
  { id: "milanesa-pollo", name: "Milanesa de pollo", category: "Comidas argentinas", portion: "1 unidad mediana (180 g)", calories: 390, protein: 33, carbs: 30, fat: 17 },
  { id: "medialuna", name: "Medialuna", category: "Comidas argentinas", portion: "1 unidad (60 g)", calories: 220, protein: 5, carbs: 27, fat: 10 },
  { id: "asado", name: "Asado", category: "Comidas argentinas", portion: "1 porción (150 g)", calories: 360, protein: 31, carbs: 0, fat: 25 },
  { id: "dulce-leche", name: "Dulce de leche", category: "Comidas argentinas", portion: "1 cucharada (20 g)", calories: 64, protein: 1.1, carbs: 11, fat: 1.5 },
  { id: "aceite", name: "Aceite de oliva", category: "Extras", portion: "1 cucharada (15 ml)", calories: 119, protein: 0, carbs: 0, fat: 13.5 },
  { id: "almendras", name: "Almendras", category: "Extras", portion: "1 puñado (30 g)", calories: 174, protein: 6.4, carbs: 6, fat: 15 },
  { id: "mantequilla-mani", name: "Pasta de maní", category: "Extras", portion: "1 cucharada (16 g)", calories: 94, protein: 4, carbs: 3, fat: 8 },
  { id: "hummus", name: "Hummus", category: "Extras", portion: "1/4 taza (60 g)", calories: 166, protein: 4.7, carbs: 14, fat: 9.6 },
];
